@startuml

title Cas d'utilisation du système de caisse

actor "Client" as client

rectangle "Caisse" as caisse {
usecase "1. Chercher un produit" as search
usecase "2. Consulter état d'un produit" as check_stock
usecase "3. Enregistrer vente" as register_sale
usecase "4. Annuler vente" as cancel_sale
}

client -left-> caisse

note bottom of caisse
    Les cas d'utilisation sont numérotés en ordre d'implémentation.
    Le cas d'utilisation "Chercher un produit" est le premier à 
    être implémenté puisque les autres cas d'utilisation en dépendent.
end note
        
@enduml